Voed 5
GyKevin/voedselbank pull request #12
Opened 2023-06-13 12:49 UTC by MrPotato-04

2023-06-13 13:21 UTC, RalkeyOfficial requested changes
You create your api structure in a way that requires more folders 
(`server/api/producten/get/[ean].ts`)
(where `/get/` is the folder)

I recommend using the right method for the right job to avoid unnecessary folders.
By putting the method needed in the file name.
`server/api/producten/index.get.ts` -- get all products
`server/api/producten/[ean].get.ts` -- get specific products
`server/api/producten/index.post.ts` -- add new product
`server/api/producten/[ean].delete.ts` -- delete specific product
`server/api/producten/[ean].put.ts` -- update specific product

This is also how the rest of the project's endpoints are (supposed to be) made.

Also, a producten endpoint already exists at `server\api\overzicht\producten`.
Please pull the latest from dev and migrate to there for consistency.

2023-06-13 13:21 UTC, RalkeyOfficial commented on pages/producten/edit/[ean].vue
> +        method: "POST",
It would be much cleaner to use the `PUT` and `DELETE` method's instead of creating a edit and delete endpoint

2023-06-13 13:21 UTC, RalkeyOfficial commented on server/api/producten/add.post.ts
> +        console.log(results);
You have left some `console.log`'s in your code

2023-06-13 13:21 UTC, RalkeyOfficial commented on server/api/producten/add.post.ts
> +        console.log(error.errno);
remove `console.log`

2023-06-13 13:21 UTC, RalkeyOfficial commented on server/api/producten/index.post.ts
> +        console.log(search);
remove `console.log`

2023-06-13 13:21 UTC, RalkeyOfficial commented on server/api/producten/index.post.ts
> +            console.log(search);
remove `console.log`

2023-06-15 13:52 UTC, Potat04 commented on pages/producten/edit/[ean].vue
> +        method: "POST",
fixed in [commit ](https://github.com/GyKevin/voedselbank/pull/12/commits/a405a9a5fd0007bb9dd1fd4d71531a65e7105b2b)

2023-06-15 14:37 UTC, RalkeyOfficial approved these changes

2023-06-15 19:51 UTC, merged